name: End-to-End Tests
on:
    push:
        paths-ignore:
            - '**.md'
    workflow_dispatch:
jobs:
    test:
        timeout-minutes: 60

        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Use Node.js 20
                uses: actions/setup-node@v4
                with:
                    node-version: '20'
                    cache: 'npm'

            -   name: Prepare express-server
                run: |
                    # Browse to the express-server example
                    cd examples/express-server
                    # Prepare the environment variables
                    cp .env.example .env
                    cp crowdsec/.env.example crowdsec/.env
                    # Install the dependencies
                    npm --prefix ../.. ci
                    npm ci
                    npm --prefix ../.. run build
                    # Install Playwright Browsers
                    npx playwright install --with-deps
                    # Start docker services
                    docker compose up -d
                    # Create a bouncer with the "crowdsec/.env" file bouncer key
                    BOUNCER_KEY=$(grep -o -E "BOUNCER_KEY=(.*)" crowdsec/.env | cut -d'=' -f2 | tr -d "'")   
                    docker exec -i nodejs-cs-crowdsec sh -c 'cscli bouncers add NodeBouncer --key $BOUNCER_KEY'

            -   name: Run Playwright tests
                run: |
                    cd examples/express-server
                    E2E_TEST_NAME=live-mode npx playwright test live-mode
                    E2E_TEST_NAME=stream-mode npx playwright test stream-mode

            -   uses: actions/upload-artifact@v4
                if: ${{ !cancelled() }}
                with:
                    name: playwright-report
                    path: examples/express-server/playwright-report/
                    retention-days: 10
